Crickets (& reorganisation of bud burst scripts)
LTER-LIFE/FDFDT pull request #10
Opened 2024-02-26 16:15 UTC by CherineJ

2024-02-29 08:18 UTC, StefanVriend requested changes
Good stuff. Again only a few minor suggestions and changes.

Looking at some files, I was wondering why they are there (and where in the scripts they are written to file). What am I missing?

- data/gryllus.txt
- data/meta_info_gryllus.txt
- data/meta_info_plantchem.txt
- data/plantchem.csv

2024-02-29 08:18 UTC, StefanVriend commented on R/budburst/01_budburst_retrieveData-SQLServer.R
> +                    "| Observer | Department intern ID of observer |  ",
```suggestion
                    "| Observer | Internal ID of observer |  ",
```

2024-02-29 08:18 UTC, StefanVriend commented on R/budburst/03_budburst_create-EML-xml.R
> +packageId <- "105c879f-a2b1-478f-9abf-56f79d0bbb9f"
We've said this before, but I think it would be good if we would track the assignment of UUIDs. We could create a function `assign_uuid()` that stores the UUID and the name of the dataset in a table. This table can then be used in a situation like this to get the right UUID.

2024-02-29 08:18 UTC, StefanVriend commented on R/crickets/crickets-map-to-DarwinCore.R
> +  dplyr::mutate(eventID = paste0(paste0(substring(Block, 1, 2), substring(Block, 4, 4)), Treat))
```suggestion
  dplyr::mutate(eventID = paste0(substring(Block, 1, 2), substring(Block, 4, 4), Treat))
```
Wouldn't this result in the same?

2024-02-29 08:18 UTC, StefanVriend commented on R/crickets/crickets-map-to-DarwinCore.R
> +                individualCount = NA,
Given our discussion on this the other day, could we fill anything in if we replace `individualCount` by `organismQuantity` (and `organismQuantityType`)?

2024-02-29 08:18 UTC, StefanVriend commented on R/crickets/crickets-map-to-DarwinCore.R
> +  dplyr::mutate(measurementID = paste(occurrenceID, 1:n(), sep = "_"), .by = "eventID")
```suggestion
  dplyr::mutate(measurementID = paste(occurrenceID, 1:dplyr::n(), sep = "_"), .by = "eventID") 
```

2024-02-29 08:18 UTC, StefanVriend commented on R/crickets/crickets-map-to-DarwinCore.R
> +  tidyr::pivot_longer(cols = Lime:batch11, names_to = "variable", values_to = "measurementValue") %>%
```suggestion
  tidyr::pivot_longer(cols = "Lime":"batch11", names_to = "variable", values_to = "measurementValue") %>% 
```

2024-02-29 08:18 UTC, StefanVriend commented on R/crickets/crickets-map-to-DarwinCore.R
> +  dplyr::mutate(dplyr::across(dplyr::everything(), as.character)) %>%
```suggestion
  dplyr::mutate(dplyr::across(tidyselect::everything(), as.character)) %>%
```

2024-02-29 08:18 UTC, StefanVriend commented on R/crickets/crickets-map-to-DarwinCore.R
> +  dplyr::mutate(measurementID = paste(occurrenceID, 1:n(), sep = "_"), .by = "eventID") %>%
```suggestion
  dplyr::mutate(measurementID = paste(occurrenceID, 1:dplyr::n(), sep = "_"), .by = "eventID") %>%
```

2024-02-29 08:18 UTC, StefanVriend commented on R/crickets/crickets-map-to-DarwinCore.R
> +
```suggestion
library(stringr)
library(tidyselect)

```

2024-02-29 08:18 UTC, StefanVriend commented on R/crickets/crickets_create_EML-xml.R
> +                                  citation = list(bibtex = "@article{vogels2021restore,
If you have a DOI, you can create a bibtex in R like this:
```
doi <- "10.3389/fevo.2021.659363"
rcrossref::cr_cn(doi, format = "bibtex")
```

2024-02-29 08:18 UTC, StefanVriend commented on R/crickets/crickets_create_EML-xml.R
> +xml2::xml_set_attr(userId_node, attr = "directory", value = "info:eu-repo/dai/nl/")
I think that directories should ideally resolve to a URL. Would that be possible in this case?

2024-02-29 08:18 UTC, StefanVriend commented on R/crickets/crickets_create_EML-xml.R
> +# Set title attribute
```suggestion
# Set directory attribute
```

2024-02-29 08:18 UTC, StefanVriend commented on R/crickets/crickets_create_EML-xml.R
> +                                                       southBoundingCoordinate = "52.04231849823671"))
Where do these coordinates come from? I ask because they are veryyyy precise. That is, decimal degrees with a precision of 7 decimal places is precise to ~1 cm (see https://en.wikipedia.org/wiki/Decimal_degrees), so 14 decimal places must be close to the scale of a nanometer. I would suggest rounding them to a "lower" precision.

2024-02-29 08:18 UTC, StefanVriend commented on R/crickets/crickets-map-to-DarwinCore.R
> +  tidyr::pivot_longer(cols = P:NPmol, names_to = "variable", values_to = "measurementValue") %>%
```suggestion
  tidyr::pivot_longer(cols = "P":"NPmol", names_to = "variable", values_to = "measurementValue") %>%
```

2024-02-29 08:18 UTC, StefanVriend commented on R/crickets/crickets-map-to-DarwinCore.R
> +                                                     variable %in% c("Cmol", "Nmol") ~ "elemental CNS analyzer",
What does CNS mean here?

2024-02-29 08:18 UTC, StefanVriend commented on R/crickets/crickets-map-to-DarwinCore.R
> +  dplyr::distinct(., eventID, .keep_all = TRUE) %>%
```suggestion
  dplyr::distinct(eventID, .keep_all = TRUE) %>% 
```

2024-02-29 08:18 UTC, StefanVriend commented on R/crickets/crickets-map-to-DarwinCore.R
> +                measurementValue = stringr::str_replace(string = measurementValue, pattern = "YES", replacement = "yes")) %>%
Nothing wrong here, but this would be a simpler alternative:
`dplyr::mutate(measurementValue = tolower(measurementValue))`

2024-02-29 08:18 UTC, StefanVriend commented on R/crickets/crickets_create_EML-xml.R
I am thinking that it would be good to write a piece of code that retrieves some of the metadata directly from the Data Station/Dataverse, so that we can fill some bits of the EML files automatically rather than manually.

This bit of code, adapted from `retrieve_dataverse_data()`, would retrieve the license info, for instance:
```
httr::GET(url = paste0("https://", server, "/api/",
                                     "datasets/:persistentId?persistentId=", dataset_doi),
                        httr::add_headers("X-Dataverse-key" = key)) |>
  httr::content(as = "text", encoding = "UTF-8") |>
  jsonlite::fromJSON() |>
  purrr::pluck("data") |>
  purrr::pluck("latestVersion") |>
  purrr::pluck("license")
```

2024-02-29 14:23 UTC, CherineJ commented on R/crickets/crickets-map-to-DarwinCore.R
> +                individualCount = NA,
Didn't we conclude in the same discussion that we can't fill anything useful in, as we actually don't know anything about the real quantity? We only know "equal volume of plant material per individual plot" was collected by "clipping aboveground living biomass" from the two plant species. I would guess this is even for the more flexible `organismQuantity ` a bit too vague, or not?

2024-02-29 14:27 UTC, CherineJ commented on R/crickets/crickets-map-to-DarwinCore.R
> +
wasn't sure whether to include `library(stringr)` as it is imported through sourcing the dataverse script

2024-02-29 14:43 UTC, CherineJ commented on R/crickets/crickets_create_EML-xml.R
> +                                                       southBoundingCoordinate = "52.04231849823671"))
Coming from the spatial coverage in the metadata on the Data Station. But I can still round them.

2024-03-01 08:12 UTC, StefanVriend commented on R/crickets/crickets-map-to-DarwinCore.R
> +                individualCount = NA,
Right, we said that indeed. I was just thinking about whether we should go for `organismQuantity` by default, following the advise you wrote in the Rulebook. But we could also make that change at a later moment.

2024-03-01 12:13 UTC, CherineJ commented on R/crickets/crickets-map-to-DarwinCore.R
> +                                                     variable %in% c("Cmol", "Nmol") ~ "elemental CNS analyzer",
It's carbon, nitrogen and sulfur. The machine they used for the analysis was called like that in the publication.

2024-03-01 12:19 UTC, CherineJ commented on R/crickets/crickets_create_EML-xml.R
> +xml2::xml_set_attr(userId_node, attr = "directory", value = "info:eu-repo/dai/nl/")
I'm not sure what the URL would be. But the EML documentations say the following: 

> This will generally
>                       be a URL that shows how to look up information, for
>                       example an LDAP URL. However, it could also be a
>                       non-parsable description of the directory system if
>                       that is all that is available.

So I guess, like it is now would also work?

2024-03-01 12:29 UTC, StefanVriend commented on R/crickets/crickets_create_EML-xml.R
> +xml2::xml_set_attr(userId_node, attr = "directory", value = "info:eu-repo/dai/nl/")
Yeah, that is definitely fine and fitting with the description. I was just wondering whether there was a more straightforward alternative, where combining the directory and the actual id would have a clear landing page of sorts.

2024-03-01 13:38 UTC, StefanVriend approved these changes
🥳 splendid!

2024-03-01 13:46 UTC, merged